# Generated by Django 4.1.7 on 2023-05-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='job_city',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='profile_image',
        ),
    ]
