# Generated by Django 4.1.7 on 2023-05-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_resume_job_city_remove_resume_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
