# Generated by Django 4.1.7 on 2023-05-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_resume_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='student',
        ),
    ]
