# Generated by Django 4.1.7 on 2023-05-10 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_salary_alter_company_seats'),
        ('student', '0012_remove_resume_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
