# Generated by Django 4.1.7 on 2023-06-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_resume_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.CharField(default=' ', max_length=40),
            preserve_default=False,
        ),
    ]
