# Generated by Django 4.1.7 on 2023-06-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_student_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.CharField(choices=[('Amritsar', 'Amritsar'), ('Mohali Campus 1 ', 'Mohali Campus 1 '), ('Hoshiarpur', 'Hoshiarpur'), ('Mohali Campus 2 ', 'Mohali Campus 2 ')], max_length=40),
        ),
    ]
